### ISSUE TITLE
training on raw images

### ISSUE THREAD

**Issue by WillieMaddox** [blackecho/Deep-Learning-TensorFlow#26]
I noticed your examples read in binary data from mnist, cifar, etc. but I'm not finding any examples that just train on a bunch of raw image files.  Does yadlt have this capability?

Thanks

**Comment by blackecho** [comment]
No, for now yadlt doesn't have that capability, you have to pre-process the images first and then pass the numpy arrays to it. Scipy makes it very easy to [load image files](http://www.scipy-lectures.org/advanced/image_processing/).

**Comment by WillieMaddox** [comment]
Great, just wanted to check first before doing any unnecessary scripting.
Thanks!
