### ISSUE TITLE
DenoisingAutoencoder._train_model args mismatch with parent UnsupervisedModel.

### ISSUE THREAD

**Issue by WillieMaddox** [blackecho/Deep-Learning-TensorFlow#32]
I noticed that the args signature in the `DenoisingAutoencoder._train_model` differs from that of its' parent `UnsupervisedModel._train_model`.  Specifically, the second and third arguments are swapped.  

```python
def _train_model(self, train_set, validation_set, train_ref=None, validation_ref=None):
```
vs.
```python
def _train_model(self, train_set, train_labels, validation_set, validation_labels):
```

Is this the intended behavior?

Thanks

**Comment by blackecho** [comment]
It was not intended, thanks for finding it!
