### ISSUE TITLE
Check the requirements to run on Python 3.5

### ISSUE THREAD

**Issue by eduarger** [blackecho/Deep-Learning-TensorFlow#35]
I was trying to run Deep Belief networks on python 3.5 and TensorFlow on windows, but when a I run the example code of the DBN (**run_dbn.py**), I found an issue with the module **cPickle**, are you aware of that error? **Are there more issues than prevents the current version to work on python 3.5?**

thanks in advance

BR

**Comment by Jorba123** [comment]
I guess you installed this project using pip because this is fixed in the current version of the code in the repo.

Just clone the code and do a manual install or just update the code in utils.datasets yourself.

**Comment by blackecho** [comment]
I just uploaded the latest version to pypi, it should be fixed now.
