### ISSUE TITLE
ImportError: No module named 'tqdm'

### ISSUE THREAD

**Issue by primasanjaya** [blackecho/Deep-Learning-TensorFlow#37]
Hi, i followed the instruction to clone project:

i run this in Windows 10 with Gitbash software.

1. pip install 
i'm quite sure it is already installed because if i install it again i found this message.
Requirement already satisfied: yadlt in c:\users\lab2\appdata\local\programs\python\python35\lib\site-packages

2. i didn't change my directory and clone the project by insterting:
git clone https://github.com/blackecho/Deep-Learning-TensorFlow.git

3. when i run cmd_line/boltzmann/run_dbn.py i got this following error.

Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    from yadlt.models.boltzmann import dbn
  File "C:\Users\LAB2\AppData\Local\Programs\Python\Python35\lib\site-packages\yadlt\models\boltzmann\dbn.py", line 8, in <module>
    from tqdm import tqdm
ImportError: No module named 'tqdm'

Thank you for any help

**Comment by blackecho** [comment]
Hi! You are missing the [`tqdm`](https://github.com/tqdm/tqdm#installation) dependency:
Run `pip install tqdm` to install it.

**Comment by mo-mahdi** [comment]
I have the same problem. and i installed tqdm but still have the same problem! can you help me?
