### ISSUE TITLE
ImportError: No module named 'tensorflow.models'

### ISSUE THREAD

**Issue by Miopas** [blackecho/Deep-Learning-TensorFlow#39]
The version of TF that I installed is 1.0. I met the error when I ran run_dbn.py. Maybe there is something different in the 1.0 TF?

```
Traceback (most recent call last):
  File "run_dbn.py", line 5, in <module>
    from yadlt.utils import datasets, utilities
  File "/usr/local/lib/python3.5/site-packages/yadlt/utils/datasets.py", line 8, in <module>
    from tensorflow.models.rnn.ptb import reader
ImportError: No module named 'tensorflow.models'
```

**Comment by blackecho** [comment]
Yes, tf 1.0 changed a lot of things, I still have to update the code to the latest tf version. I hope to do it in the following days.

**Comment by blackecho** [comment]
It should work now.

**Comment by FatDoge** [comment]
It still doesn't work now,I get the same ErrInfo.
