### ISSUE TITLE
Problem with run_conv_net.py

### ISSUE THREAD

**Issue by King-Of-Knights** [blackecho/Deep-Learning-TensorFlow#42]
Traceback (most recent call last):
  File "/home/saber/Desktop/Deep-Learning-TensorFlow-master/cmd_line/convolutional/run_conv_net.py", line 90, in <module>
    convnet.fit(trX, trY, vlX, vlY)
  File "/usr/local/lib/python2.7/dist-packages/yadlt/core/supervised_model.py", line 62, in fit
    self.build_model(train_X.shape[1], num_classes)
  File "/usr/local/lib/python2.7/dist-packages/yadlt/models/convolutional/conv_net.py", line 109, in build_model
    self.cost = self.loss.compile(self.mod_y, self.input_labels)
AttributeError: 'ConvolutionalNetwork' object has no attribute 'mod_y'
I got this problem,have no idea, Any help will be appreciated! Thank you!
I directly run run_conv_net.py. It leaded the error?

**Comment by King-Of-Knights** [comment]
Issues solved! It took me a long time  to sovle it. I shouldn't directly run run_conv_net and should modify the Cmd example usage to make it trained by Mnist. What's more, it's weird that TensorFLow 0.12.0 above will work. 0.8.0-0.11.0 always miss something module.

**Comment by King-Of-Knights** [comment]
But when I run "python run_dbn.py --dataset mnist --main_dir dbn-models --model_name my-deeper-dbn  --verbose 1 --rbm_layers 512,256 --rbm_learning_rate 0.005 --rbm_num_epochs 15 --rbm_batch_size 25 --finetune_batch_size 25 --finetune_learning_rate 0.001 --finetune_num_epochs 10 --finetune_loss_func softmax_cross_entropy --finetune_dropout 0.7 --finetune_act_func relu"
It tells me that
  File "run_dbn.py", line 114, in <module>
    finetune_dropout=FLAGS.finetune_dropout)
  File "/usr/local/lib/python2.7/dist-packages/yadlt/models/boltzmann/dbn.py", line 59, in __init__
    momentum=momentum)
  File "/usr/local/lib/python2.7/dist-packages/yadlt/core/trainers.py", line 51, in __init__
    use_nesterov=d("use_nesterov", False))
  File "/usr/local/lib/python2.7/dist-packages/yadlt/core/trainers.py", line 33, in d
    return kw[k]
KeyError: 'use_nesterov'
looks like the 'use_nesterov' doesn't exsit in the dictionary. I hope you are aware of it, Thanks a lot!!!\

**Comment by blackecho** [comment]
Hi! Sorry for the late response!
The 'use_nesterov' issue is now fixed in the latest master branch code. I guess I should also update the pip package to this new version.

**Comment by King-Of-Knights** [comment]
Yes! Every time I install it, it is still the old version. However, Thanks for your Contribution~~

**Comment by blackecho** [comment]
Ok, now you should be able to get the latest version from pip :smile:

**Comment by King-Of-Knights** [comment]
I just hurry to my home and it.....just works!!! You guys just like a wizard! :100:  I will study your code one line by one line and try to figure out what is going on there~ Thanks again!! I hope I can contribute to it one day~~:-)
