### ISSUE TITLE
conv net fails in build model

### ISSUE THREAD

**Issue by ingo1807** [blackecho/Deep-Learning-TensorFlow#45]
Hi! I really like this repository it's super useful! I'm working on a CNN and wanted to use yours as starting position. Now there is a problem in the conv_net.py (line 111). Commit: a038e15

    self.cost = self.loss.compile(self.mod_y, self.input_labels)
AttributeError: 'ConvolutionalNetwork' object has no attribute 'mod_y'

Tried to run it on the MNIST dataset with all the default settings. Hope you can help!

**Comment by blackecho** [comment]
Hi! Thanks for appreciating my work!
I just ran the example on my local machine and it works fine. Can you please check if you're using "softmax" as the last layer of the `--layers` option? It should be something like `--layers conv2d-5-5-32-1,maxpool-2,conv2d-5-5-64-1,maxpool-2,full-1024,softmax`

**Comment by ingo1807** [comment]
Ah my bad! I didn't realise that the layers default string was empty. Well Now it seems to run perfectly :)  Thanks for the quick reply and please keep working on this repo, it's great!!
