### ISSUE TITLE
deep bolztman machine reconstruction error

### ISSUE THREAD

**Issue by haluk** [blackecho/Deep-Learning-TensorFlow#46]
How do we fix the error that stem from the following line:
https://github.com/blackecho/Deep-Learning-TensorFlow/blob/f859d6e6cc58162363d8076e56c005545927c0c7/cmd_line/boltzmann/run_deep_autoencoder.py#L155

**Comment by blackecho** [comment]
I just fixed this with the latest commit, thanks for reporting this issue!
