### ISSUE TITLE
Import Error on example with convolutional net

### ISSUE THREAD

**Issue by Wermarter** [blackecho/Deep-Learning-TensorFlow#47]
I'm running this:

> python cmd_line/convolutional/run_conv_net.py --dataset custom --main_dir convnet-models --model_name my.Awesome.CONVNET --train_dataset path/to/train_set.npy --valid_dataset path/to/valid_set.npy --test_set path/to/test_set.npy --layers conv2d-5-5-32-1,maxpool-2,conv2d-5-5-64-1,maxpool-2,full-1024,softmax --batch_size 50 --verbose 1 --learning_rate 1e-4 --opt adam --dropout 0.5

and get:

> Traceback (most recent call last):
  File "cmd_line/convolutional/run_conv_net.py", line 4, in <module>
    from yadlt.models.convolutional import conv_net
ImportError: No module named 'yadlt'

I'm a Pynoob trying to import this to python 3 but get stuck at this error.

**Comment by CharleyPeng1** [comment]
Did you install yadlt? `pip install yadlt`

**Comment by Wermarter** [comment]
Sorry I didn't. But how should I deal with this in the development of process of my own lib?
How can I import from another parent directory in python 3?

**Comment by CharleyPeng1** [comment]
https://docs.python.org/3/tutorial/modules.html#intra-package-references

**Comment by sun137653577** [comment]
I have installed yadlt, while run:
python cmd_line/convolutional/run_conv_net.py --dataset custom --main_dir convnet-models --model_name my.Awesome.CONVNET --train_dataset path/to/train_set.npy --valid_dataset path/to/valid_set.npy --test_set path/to/test_set.npy --layers conv2d-5-5-32-1,maxpool-2,conv2d-5-5-64-1,maxpool-2,full-1024,softmax --batch_size 50 --verbose 1 --learning_rate 1e-4 --opt adam --dropout 0.5
 
, it shown following error, do you know why?

Traceback (most recent call last):
  File "cmd_line/convolutional/run_conv_net.py", line 73, in <module>
    trX, trY = load_from_np(FLAGS.train_dataset), load_from_np(FLAGS.train_labels)
  File "cmd_line/convolutional/run_conv_net.py", line 68, in load_from_np
    return np.load(dataset_path)
  File "/Users/za-sunjianju/anaconda/lib/python2.7/site-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: 'path/to/train_set.npy'

**Comment by wermarter** [comment]
@sun137653577 
You just forgot to specify the `path/to/train_set.npy` in your command. Good luck.
Btw I forgot to close this issue.
