### ISSUE TITLE
Add to PyPi

### ISSUE THREAD

**Issue by Jakobovski** [blackecho/Deep-Learning-TensorFlow#7]
Thanks for the great repository! 👍

I'm wondering if you could add this repository to PyPi so that it can be installed using PIP. This would be particularly useful for people who are not using it from the command line and need to import its models into their existing projects.

Cheers

**Comment by blackecho** [comment]
Hi @Jakobovski.

I agree. I'll add the repo to PyPi as soon as possible :+1:

**Comment by blackecho** [comment]
I just added the repo to PyPi. I will add it to the documentation after some testing.
If you would like to try it, you can install the package with `pip install yadlt`.
The models are available with `from yadlt.models.autoencoder_models import denoising_autoencoder` for example.

Cheers

**Comment by Jakobovski** [comment]
Thanks. I think you should remove the `rc0` from the requirements. 

See screenshot https://www.dropbox.com/s/tynt0z01v5bzn7h/Screenshot%202016-05-16%2020.20.35.png?dl=0

I was able to install it anyways by forcing pip to ignore dependencies `pip install yadlt --no-deps`

**Comment by blackecho** [comment]
Thanks for reporting this error. I think I will just remove tensorflow from the requirements so that people can install it separately :+1:
